# Numpy


In [1]:
# Importing module
import numpy as np

# Creating Arrays

In [ ]:
help(np.array)

In [5]:
# Creating a 1D array: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
print("x:", x)
print("shape:", x.shape)

x: [1 2 3]
shape: (3,)


In [6]:
type(x)

numpy.ndarray

In [7]:
# Creating a 2D array: nested lists
l = [[1, 2], [3, 4]]
x = np.array(l)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[1 2]
 [3 4]]
shape: (2, 2)


In [8]:
# Array with 0's
dim = (2,2) # (lines, columns)
x = np.zeros(dim)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[0. 0.]
 [0. 0.]]
shape: (2, 2)


In [9]:
# Array with 1's
dim = (2,2) # (lines, columns)
x = np.ones(dim)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[1. 1.]
 [1. 1.]]
shape: (2, 2)


In [11]:
# creating values inside an interval
# uniform values between 5 and 15

x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=6)
print("x:", x)
print("shape:", x.shape)

x: [ 5.  7.  9. 11. 13. 15.]
shape: (6,)


In [12]:
# creating identity matrix
n = 4
x = np.eye(n)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape: (4, 4)


In [13]:
# random values
# np.random.seed(10)
x = np.random.random(size=(2, 3))
print("x:\n", x)
print("shape:", x.shape)

x:
 [[0.91364277 0.58447993 0.35325854]
 [0.89223046 0.02100358 0.52700308]]
shape: (2, 3)
